spring:
  config:
    activate:
      on-profile: dev

  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        tags:
          - profile=${spring.profiles.active}
          - version='@project.version@'
          - git-version=${git.commit.id.describe:}
          - git-commit=${git.commit.id.abbrev:}
          - git-branch=${git.branch:}
      host: localhost
      port: 8500

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: myFirstMicroService
    password: mySecurePassword
    hikari:
      poolName: Hikari
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.sample: DEBUG


aws:
  s3:
    bucket-name: my-local-bucket
    input-folder: input/
    output-folder: output/

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: us-east-1
    endpoint: http://localhost:4566


